# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_LKSS_DRIVERS_LAB2)	+= ex1/simple_char.o
obj-$(CONFIG_LKSS_DRIVERS_LAB2)	+= ex2/mytimer.o
obj-$(CONFIG_LKSS_DRIVERS_LAB2_EX3)	+= ex3/gpio_led_ioctl.o
obj-$(CONFIG_LKSS_DRIVERS_LAB2_EX4)	+= ex4/gpio_led_button.o
